#!/bin/bash
npm start

# We run the Python app after the wifi connection has been established
cd /app && python main.py

while true
do
	echo "App exited but container is still running to allow web terminal access"
	sleep 3600
done
